apiVersion: v1
kind: Service
metadata:
  name: intranet-newdeal-service
  namespace: default
  labels:
    app: intranet-newdeal
spec:
  type: NodePort
  selector:
    app: intranet-newdeal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
